white_lower_h: 0
white_lower_s: 0
white_lower_v: 134
white_upper_h: 179
white_upper_s: 70
white_upper_v: 255
yellow_lower_h: 22
yellow_lower_s: 80
yellow_lower_v: 98
yellow_upper_h: 120
yellow_upper_s: 255
yellow_upper_v: 255
